TIME_SPENT_PREPROCESSING = 0
TIME_SPENT_CALCULATING = 0
TIME_SPENT_LOADING = 0
TIME_SPENT_COMPRESSING = 0
TIME_SPENT_DECOMPRESSING = 0
TIME_SPENT_WRITING = 0

TIME_SPENT_CALCULATING_UNOPTIMISABLE = 0

SHOULD_MEASURE_IO = True